# Generated by Django 4.2.26 on 2026-02-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating_data',
            name='user',
        ),
    ]
