# Generated by Django 4.2.26 on 2026-02-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymental', '0002_remove_rating_data_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating_data',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating_data',
            name='mood_rating',
            field=models.IntegerField(
                choices=[(1, '😢'), (2, '😔'), (3, '😐'), (4, '😊'), (5, '😁')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating_data',
            name='productivity_rating',
            field=models.IntegerField(
                choices=[(1, '😢'), (2, '😔'), (3, '😐'), (4, '😊'), (5, '😁')], default=3),
            preserve_default=False,
        ),
    ]
