# Generated by Django 4.2.26 on 2026-02-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymental', '0003_remove_rating_data_rating_rating_data_mood_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_data',
            name='mood_rating',
            field=models.IntegerField(
                choices=[(1, '😢'), (2, '😔'), (3, '😐'), (4, '😊'), (5, '😁')], default=3),
        ),
        migrations.AlterField(
            model_name='rating_data',
            name='productivity_rating',
            field=models.IntegerField(
                choices=[(1, '😢'), (2, '😔'), (3, '😐'), (4, '😊'), (5, '😁')], default=3),
        ),
    ]
