# Generated by Django 4.2.26 on 2026-02-27 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymental', '0004_alter_rating_data_mood_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating_data',
            name='user',
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
