# Generated by Django 4.2.26 on 2026-02-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymental', '0005_rating_data_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating_data',
            name='user',
        ),
    ]
