# Generated by Django 4.2.26 on 2026-03-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymental', '0008_to_do_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='task_title',
            field=models.CharField(max_length=24),
        ),
    ]
